version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qarzuz_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL:-file:./dev.db}
      - PORT=${PORT:-3001}
      - JWT_SECRET=${JWT_SECRET:-default_secret_key}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/prisma:/app/prisma
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./telegram-web-app
      dockerfile: Dockerfile
    container_name: qarzuz_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:3001}
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: qarzuz_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-qarzuz}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge